import styles from "./page.module.css";
import Image from "next/image";

import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
});

const About = () => {
  return (
    <>
      <h1 className={styles.title}>About</h1>
      <div className={`${roboto.className} ${styles.container}`}>
        <div className={styles.cardContainer}>
          <div className={styles.card}>
            <h2 className={styles.cardTitle}>About Wardu Tech</h2>
            <div className={styles.profileContainer}>
              <Image
                className={styles.profile}
                src='/profile.png'
                alt='Wardu Profile Photo'
                width={200}
                height={200}
              />
            </div>
            <p className={styles.cardText}>
              Welcome to Wardu Tech (WT). We offer a unique suite of services,
              tailored specifically for the motorcycle mechanics and tuners
              industry:
            </p>
          </div>
          <ul>
            <li>
              <h3>Industry-Specific Web Design</h3>
              <p>
                We specialise in creating visually appealing, easy-to-navigate
                websites that reflect the aesthetics of the motorcycle industry.
                Integrating motorcycle-related imagery, a strong and bold colour
                scheme, and a layout that represents the gritty, mechanical
                nature of the field.
              </p>
            </li>
            <li>
              <h3>Custom Web Development</h3>
              <p>
                Our high-performance websites load quickly and are
                mobile-friendly (over 60% of web traffic is generated by mobile
                usage). Showcase your work with a dynamic gallery featuring
                before-and-after motorcycle tuning shots, collect glowing client
                testimonials, share industry tips and tricks via a dedicated
                blog, and answer common queries in an FAQ section.
              </p>
            </li>
            <li>
              <h3>SEO and Digital Marketing</h3>
              <p>
                Search engine optimization (SEO) tailored for the motorcycle
                repair industry, content marketing strategies involving blog
                posts and articles about motorcycle maintenance, and social
                media marketing to engage with customers and showcase their
                work.
              </p>
            </li>
            <li>
              <h3>Maintenance and Support</h3>
              <p>
                Post-launch, we provide consistent website maintenance to ensure
                your site remains updated, secure, and running smoothly.
                Services include regular backups, security updates, and
                troubleshooting.
              </p>
            </li>
          </ul>
          <div>
            <h2>Our Promise</h2>
            <p>
              If you're serious about maximising the return on your investment
              in web design and SEO for your motorcycle mechanics and tuners
              business, then you've landed at the right place. WT's specific
              niche focus gives us a competitive edge, allowing us to deeply
              understand the needs of our clients and provide superior, tailored
              solutions.
            </p>

            <p>
              At WT, we're not just creating appealing websites; we're
              fashioning high-performance digital platforms that generate real
              results. Our proven experience in this niche, combined with our
              commitment to transparent, honest communication sets us apart.
              We're your consultants, not salespeople, and we're here to guide
              you based on your unique needs.
            </p>

            <h2>Ready to Rev Up Your Online Presence?</h2>
            <p>
              We're so confident in our skills and the calibre of our work, that
              we back each project with a 100% refund guarantee.
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default About;
